letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ!. '
write=False

def drawBoard(board,board2,board3,board4,board6,frame=False,numbers=False,instructions=False):
    if frame==False and numbers==True:
        HLINE = '  +---------+---------+---------+---------+---------+---------+---------+---------+'
        VLINE = '  |         |         |         |         |         |         |         |         |'

        print('       a         b         c         d         e         f         g         h')
        print(HLINE)
        m=8
        for y in range(8):
            print('',end='  ')
            for x in range(8):
                print('|%s' % (board3[x][y]),end='')
            print('|')
            print(m, end=' ')
            for x in range(8):
                print('|%s%s%s' % (board4[x][y],board[y][x],board6[x][y]),end='')
            print('|',m)
            print('',end='  ')
            for x in range(8):
                print('|%s%s%s' % (board4[x][y],board2[y][x],board6[x][y]),end='')
            print('|')
            print(HLINE)
            m-=1
        print('       a         b         c         d         e         f         g         h\n')
        
    elif frame==True and numbers==True:
        frame = '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
        HLINE = '  +---------+---------+---------+---------+---------+---------+---------+---------+'
        VLINE = '  |         |         |         |         |         |         |         |         |'

        print(frame)
        print('!       a         b         c         d         e         f         g         h       !')
        print('!%s  !'%(HLINE))
        m=8
        for y in range(8):
            print('!',end='  ')
            for x in range(8):
                print('|%s' % (board3[x][y]),end='')
            print('|  !')
            print('!%s' %(m),end=' ')
            for x in range(8):
                print('|%s%s%s' % (board4[x][y],board[y][x],board6[x][y]),end='')
            print('| %s!'%(m))
            print('!',end='  ')
            for x in range(8):
                print('|%s%s%s' % (board4[x][y],board2[y][x],board6[x][y]),end='')
            print('|  !')
            print('!%s  !'%(HLINE))
            m-=1
        print('!       a         b         c         d         e         f         g         h       !')
        print('%s\n' %(frame))
        
    elif frame==False and numbers==False:
        HLINE = '+---------+---------+---------+---------+---------+---------+---------+---------+'
        VLINE = '  |         |         |         |         |         |         |         |         |'

        print(HLINE)
        for y in range(8):
            for x in range(8):
                print('|%s' % (board3[x][y]),end='')
            print('|')
            for x in range(8):
                print('|%s%s%s' % (board4[x][y],board[y][x],board6[x][y]),end='')
            print('|')
            for x in range(8):
                print('|%s%s%s' % (board4[x][y],board2[y][x],board6[x][y]),end='')
            print('|')
            print(HLINE)
        
    elif frame==True and numbers==False:
        frame = '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
        HLINE = '+---------+---------+---------+---------+---------+---------+---------+---------+'
        VLINE = '  |         |         |         |         |         |         |         |         |'

        print(frame)
        print('!%s!'%(HLINE))
        m=8
        for y in range(8):
            print('!',end='')
            for x in range(8):
                print('|%s' % (board3[x][y]),end='')
            print('|!')
            print('!',end='')
            for x in range(8):
                print('|%s%s%s' % (board4[x][y],board[y][x],board6[x][y]),end='')
            print('|!')
            print('!',end='')
            for x in range(8):
                print('|%s%s%s' % (board4[x][y],board2[y][x],board6[x][y]),end='')
            print('|!')
            print('!%s!'%(HLINE))
        print('%s\n' %(frame))
        
    if instructions==True:
        print('Top letter:\n1.\'P\'=Pice(1 point)\n2.\'H\'=Night(horse)(3 points)\n3.\'B\'=Bishop(runner)(3 points)\n4.\'R\'=Roof(tower)(5 points)\n5.\'Q\'=Queen(9 points)\n6.\'K\'=King(game over)\n\nBottom letter:\n\'X\'=Black\n\'O\'=White\n\nSquares:\n\'.........\n .... .... =Black square\n .... ....\'\n\'         \n           =White square\n          \'')


def resetBoard(board,board2):
   
    board[0][0] = 'R'
    board2[0][0] = 'X'
    board[0][1] = 'H'
    board2[0][1] = 'X'
    board[0][2] = 'B'
    board2[0][2] = 'X'
    board[0][3] = 'Q'
    board2[0][3] = 'X'
    board[0][4] = 'K'
    board2[0][4] = 'X'
    board[0][5] = 'B'
    board2[0][5] = 'X'
    board[0][6] = 'H'
    board2[0][6] = 'X'
    board[0][7] = 'R'
    board2[0][7] = 'X'
    board[1][0] = 'P'
    board2[1][0] = 'X'
    board[1][1] = 'P'
    board2[1][1] = 'X'
    board[1][2] = 'P'
    board2[1][2] = 'X'
    board[1][3] = 'P'
    board2[1][3] = 'X'
    board[1][4] = 'P'
    board2[1][4] = 'X'
    board[1][5] = 'P'
    board2[1][5] = 'X'
    board[1][6] = 'P'
    board2[1][6] = 'X'
    board[1][7] = 'P'
    board2[1][7] = 'X'
    
    board[7][0] = 'R'
    board2[7][0] = 'O'
    board[7][1] = 'H'
    board2[7][1] = 'O'
    board[7][2] = 'B'
    board2[7][2] = 'O'
    board[7][3] = 'Q'
    board2[7][3] = 'O'
    board[7][4] = 'K'
    board2[7][4] = 'O'
    board[7][5] = 'B'
    board2[7][5] = 'O'
    board[7][6] = 'H'
    board2[7][6] = 'O'
    board[7][7] = 'R'
    board2[7][7] = 'O'
    board[6][0] = 'P'
    board2[6][0] = 'O'
    board[6][1] = 'P'
    board2[6][1] = 'O'
    board[6][2] = 'P'
    board2[6][2] = 'O'
    board[6][3] = 'P'
    board2[6][3] = 'O'
    board[6][4] = 'P'
    board2[6][4] = 'O'
    board[6][5] = 'P'
    board2[6][5] = 'O'
    board[6][6] = 'P'
    board2[6][6] = 'O'
    board[6][7] = 'P'
    board2[6][7] = 'O'

def getBlankChessBoard(board,board2,board3,board4,board5,board6):
    if board5=='White':
        board3[0][0]='         '
        board4[0][0]='    '
        board3[0][1]='.........'
        board4[0][1]='....'
        board3[0][2]='         '
        board4[0][2]='    '
        board3[0][3]='.........'
        board4[0][3]='....'
        board3[0][4]='         '
        board4[0][4]='    '
        board3[0][5]='.........'
        board4[0][5]='....'
        board3[0][6]='         '
        board4[0][6]='    '
        board3[0][7]='.........'
        board4[0][7]='....'

        board3[1][0]='.........'
        board4[1][0]='....'
        board3[1][1]='         '
        board4[1][1]='    '
        board3[1][2]='.........'
        board4[1][2]='....'
        board3[1][3]='         '
        board4[1][3]='    '
        board3[1][4]='.........'
        board4[1][4]='....'
        board3[1][5]='         '
        board4[1][5]='    '
        board3[1][6]='.........'
        board4[1][6]='....'
        board3[1][7]='         '
        board4[1][7]='    '

        board3[2][0]='         '
        board4[2][0]='    '
        board3[2][1]='.........'
        board4[2][1]='....'
        board3[2][2]='         '
        board4[2][2]='    '
        board3[2][3]='.........'
        board4[2][3]='....'
        board3[2][4]='         '
        board4[2][4]='    '
        board3[2][5]='.........'
        board4[2][5]='....'
        board3[2][6]='         '
        board4[2][6]='    '
        board3[2][7]='.........'
        board4[2][7]='....'

        board3[3][0]='.........'
        board4[3][0]='....'
        board3[3][1]='         '
        board4[3][1]='    '
        board3[3][2]='.........'
        board4[3][2]='....'
        board3[3][3]='         '
        board4[3][3]='    '
        board3[3][4]='.........'
        board4[3][4]='....'
        board3[3][5]='         '
        board4[3][5]='    '
        board3[3][6]='.........'
        board4[3][6]='....'
        board3[3][7]='         '
        board4[3][7]='    '

        board3[4][0]='         '
        board4[4][0]='    '
        board3[4][1]='.........'
        board4[4][1]='....'
        board3[4][2]='         '
        board4[4][2]='    '
        board3[4][3]='.........'
        board4[4][3]='....'
        board3[4][4]='         '
        board4[4][4]='    '
        board3[4][5]='.........'
        board4[4][5]='....'
        board3[4][6]='         '
        board4[4][6]='    '
        board3[4][7]='.........'
        board4[4][7]='....'

        board3[5][0]='.........'
        board4[5][0]='....'
        board3[5][1]='         '
        board4[5][1]='    '
        board3[5][2]='.........'
        board4[5][2]='....'
        board3[5][3]='         '
        board4[5][3]='    '
        board3[5][4]='.........'
        board4[5][4]='....'
        board3[5][5]='         '
        board4[5][5]='    '
        board3[5][6]='.........'
        board4[5][6]='....'
        board3[5][7]='         '
        board4[5][7]='    '

        board3[6][0]='         '
        board4[6][0]='    '
        board3[6][1]='.........'
        board4[6][1]='....'
        board3[6][2]='         '
        board4[6][2]='    '
        board3[6][3]='.........'
        board4[6][3]='....'
        board3[6][4]='         '
        board4[6][4]='    '
        board3[6][5]='.........'
        board4[6][5]='....'
        board3[6][6]='         '
        board4[6][6]='    '
        board3[6][7]='.........'
        board4[6][7]='....'

        board3[7][0]='.........'
        board4[7][0]='....'
        board3[7][1]='         '
        board4[7][1]='    '
        board3[7][2]='.........'
        board4[7][2]='....'
        board3[7][3]='         '
        board4[7][3]='    '
        board3[7][4]='.........'
        board4[7][4]='....'
        board3[7][5]='         '
        board4[7][5]='    '
        board3[7][6]='.........'
        board4[7][6]='....'
        board3[7][7]='         '
        board4[7][7]='    '
        for x in range(0,8):
            for y in range(0,8):
                board6[x][y]=board4[x][y]

    elif board5=='Black':
        board3[0][0]='.........'
        board4[0][0]='....'
        board3[0][1]='         '
        board4[0][1]='    '
        board3[0][2]='.........'
        board4[0][2]='....'
        board3[0][3]='         '
        board4[0][3]='    '
        board3[0][4]='.........'
        board4[0][4]='....'
        board3[0][5]='         '
        board4[0][5]='    '
        board3[0][6]='.........'
        board4[0][6]='....'
        board3[0][7]='         '
        board4[0][7]='    '

        board3[1][0]='         '
        board4[1][0]='    '
        board3[1][1]='.........'
        board4[1][1]='....'
        board3[1][2]='         '
        board4[1][2]='    '
        board3[1][3]='.........'
        board4[1][3]='....'
        board3[1][4]='         '
        board4[1][4]='    '
        board3[1][5]='.........'
        board4[1][5]='....'
        board3[1][6]='         '
        board4[1][6]='    '
        board3[1][7]='.........'
        board4[1][7]='....'

        board3[2][0]='.........'
        board4[2][0]='....'
        board3[2][1]='         '
        board4[2][1]='    '
        board3[2][2]='.........'
        board4[2][2]='....'
        board3[2][3]='         '
        board4[2][3]='    '
        board3[2][4]='.........'
        board4[2][4]='....'
        board3[2][5]='         '
        board4[2][5]='    '
        board3[2][6]='.........'
        board4[2][6]='....'
        board3[2][7]='         '
        board4[2][7]='    '

        board3[3][0]='         '
        board4[3][0]='    '
        board3[3][1]='.........'
        board4[3][1]='....'
        board3[3][2]='         '
        board4[3][2]='    '
        board3[3][3]='.........'
        board4[3][3]='....'
        board3[3][4]='         '
        board4[3][4]='    '
        board3[3][5]='.........'
        board4[3][5]='....'
        board3[3][6]='         '
        board4[3][6]='    '
        board3[3][7]='.........'
        board4[3][7]='....'

        board3[4][0]='.........'
        board4[4][0]='....'
        board3[4][1]='         '
        board4[4][1]='    '
        board3[4][2]='.........'
        board4[4][2]='....'
        board3[4][3]='         '
        board4[4][3]='    '
        board3[4][4]='.........'
        board4[4][4]='....'
        board3[4][5]='         '
        board4[4][5]='    '
        board3[4][6]='.........'
        board4[4][6]='....'
        board3[4][7]='         '
        board4[4][7]='    '

        board3[5][0]='         '
        board4[5][0]='    '
        board3[5][1]='.........'
        board4[5][1]='....'
        board3[5][2]='         '
        board4[5][2]='    '
        board3[5][3]='.........'
        board4[5][3]='....'
        board3[5][4]='         '
        board4[5][4]='    '
        board3[5][5]='.........'
        board4[5][5]='....'
        board3[5][6]='         '
        board4[5][6]='    '
        board3[5][7]='.........'
        board4[5][7]='....'

        board3[6][0]='.........'
        board4[6][0]='....'
        board3[6][1]='         '
        board4[6][1]='    '
        board3[6][2]='.........'
        board4[6][2]='....'
        board3[6][3]='         '
        board4[6][3]='    '
        board3[6][4]='.........'
        board4[6][4]='....'
        board3[6][5]='         '
        board4[6][5]='    '
        board3[6][6]='.........'
        board4[6][6]='....'
        board3[6][7]='         '
        board4[6][7]='    '

        board3[7][0]='         '
        board4[7][0]='    '
        board3[7][1]='.........'
        board4[7][1]='....'
        board3[7][2]='         '
        board4[7][2]='    '
        board3[7][3]='.........'
        board4[7][3]='....'
        board3[7][4]='         '
        board4[7][4]='    '
        board3[7][5]='.........'
        board4[7][5]='....'
        board3[7][6]='         '
        board4[7][6]='    '
        board3[7][7]='.........'
        board4[7][7]='....'
        for x in range(0,8):
            for y in range(0,8):
                board6[x][y]=board4[x][y]
    elif board5==' ':
        for x in range(8):
            for y in range(8):
                board[x][y] = ' '
                board2[x][y] = ' '
                board3[x][y] = '         '
                board4[x][y] = '    '
                board6[x][y] = '    '

    elif board5=='!':
        for x in range(8):
            for y in range(8):
                board[x][y] = ' '
                board2[x][y] = ' '
        board3[0][0]='         '
        board4[0][0]='    '
        board6[0][0]='    '
        board3[0][1]='         '
        board4[0][1]='    '
        board6[0][1]='    '
        board3[0][2]='         '
        board4[0][2]='    '
        board6[0][2]='    '
        board3[0][3]='         '
        board4[0][3]='    '
        board6[0][3]='    '
        board3[0][4]='         '
        board4[0][4]='    '
        board6[0][4]='    '
        board3[0][5]='         '
        board4[0][5]='    '
        board6[0][5]='    '
        board3[0][6]='         '
        board4[0][6]='    '
        board6[0][6]='    '
        board3[0][7]='         '
        board4[0][7]='    '
        board6[0][7]='    '

        

        board3[1][0]='         '
        board4[1][0]='    '
        board6[1][0]='    '
        board3[1][1]='    mmmmm'
        board4[1][1]='    '
        board6[1][1]='mmmm'
        board3[1][2]='         '
        board4[1][2]='    '
        board6[1][2]='    '
        board3[1][3]='         '
        board4[1][3]='    '
        board6[1][3]='    '
        board3[1][4]='         '
        board4[1][4]='    '
        board6[1][4]='    '
        board3[1][5]='         '
        board4[1][5]='    '
        board6[1][5]='    '
        board3[1][6]='         '
        board4[1][6]='    '
        board6[1][6]='    '
        board3[1][7]='         '
        board4[1][7]='    '
        board6[1][7]='    '

        board[1][1]='m'
        board2[1][1]='m'

        board3[2][0]='         '
        board4[2][0]='    '
        board6[2][0]='    '
        board3[2][1]='mmmmmmmmm'
        board4[2][1]='mmmm'
        board6[2][1]='mmmm'
        board3[2][2]='mmmmmmmmm'
        board4[2][2]='mmmm'
        board6[2][2]='mmmm'
        board3[2][3]='    mmmmm'
        board4[2][3]='    '
        board6[2][3]='mmmm'
        board3[2][4]='         '
        board4[2][4]='    '
        board6[2][4]='    '
        board3[2][5]='         '
        board4[2][5]='    '
        board6[2][5]='    '
        board3[2][6]='         '
        board4[2][6]='    '
        board6[2][6]='    '
        board3[2][7]='         '
        board4[2][7]='    '
        board6[2][7]='    '

        board[1][2]='m'
        board2[1][2]='m'
        board[2][2]='m'
        board2[2][2]='m'
        board[3][2]='m'
        board2[3][2]='m'

        board3[3][0]='         '
        board4[3][0]='    '
        board6[3][0]='    '
        board3[3][1]='mmmmmmmmm'
        board4[3][1]='mmmm'
        board6[3][1]='mmmm'
        board3[3][2]='mmmmmmmmm'
        board4[3][2]='mmmm'
        board6[3][2]='mmmm'
        board3[3][3]='mmmmmmmmm'
        board4[3][3]='mmmm'
        board6[3][3]='mmmm'
        board3[3][4]='mmmmmmmmm'
        board4[3][4]='mmmm'
        board6[3][4]='mmmm'
        board3[3][5]='         '
        board4[3][5]='    '
        board6[3][5]='    '
        board3[3][6]='mmmmmmmmm'
        board4[3][6]='mmmm'
        board6[3][6]='mmmm'
        board3[3][7]='mmmmmmmmm'
        board4[3][7]='mmmm'
        board6[3][7]='mmmm'

        board[6][3]='m'
        board2[6][3]='m'
        board[7][3]='m'
        board2[7][3]='m'
        board[1][3]='m'
        board2[1][3]='m'
        board[2][3]='m'
        board2[2][3]='m'
        board[3][3]='m'
        board2[3][3]='m'
        board[4][3]='m'
        board2[4][3]='m'

        board3[4][0]='         '
        board4[4][0]='    '
        board6[4][0]='    '
        board3[4][1]='mmmmmmmmm'
        board4[4][1]='mmmm'
        board6[4][1]='mmmm'
        board3[4][2]='mmmmmmmmm'
        board4[4][2]='mmmm'
        board6[4][2]='mmmm'
        board3[4][3]='mmmmmmmmm'
        board4[4][3]='mmmm'
        board6[4][3]='mmmm'
        board3[4][4]='mmmmmmmmm'
        board4[4][4]='mmmm'
        board6[4][4]='mmmm'
        board3[4][5]='         '
        board4[4][5]='    '
        board6[4][5]='    '
        board3[4][6]='mmmmmmmmm'
        board4[4][6]='mmmm'
        board6[4][6]='mmmm'
        board3[4][7]='mmmmmmmmm'
        board4[4][7]='mmmm'
        board6[4][7]='mmmm'

        board[6][4]='m'
        board2[6][4]='m'
        board[7][4]='m'
        board2[7][4]='m'
        board[1][4]='m'
        board2[1][4]='m'
        board[2][4]='m'
        board2[2][4]='m'
        board[3][4]='m'
        board2[3][4]='m'
        board[4][4]='m'
        board2[4][4]='m'
        

        board3[5][0]='         '
        board4[5][0]='    '
        board6[5][0]='    '
        board3[5][1]='mmmmmmmmm'
        board4[5][1]='mmmm'
        board6[5][1]='mmmm'
        board3[5][2]='mmmmmmmmm'
        board4[5][2]='mmmm'
        board6[5][2]='mmmm'
        board3[5][3]='mmmmm    '
        board4[5][3]='mmmm'
        board6[5][3]='    '
        board3[5][4]='         '
        board4[5][4]='    '
        board6[5][4]='    '
        board3[5][5]='         '
        board4[5][5]='    '
        board6[5][5]='    '
        board3[5][6]='         '
        board4[5][6]='    '
        board6[5][6]='    '
        board3[5][7]='         '
        board4[5][7]='    '
        board6[5][7]='    '

        board[1][5]='m'
        board2[1][5]='m'
        board[2][5]='m'
        board2[2][5]='m'
        board[3][5]='m'
        board2[3][5]='m'
        
        
        board3[6][0]='         '
        board4[6][0]='    '
        board6[6][0]='    '
        board3[6][1]='mmmmm    '
        board4[6][1]='mmmm'
        board6[6][1]='    '
        board3[6][2]='         '
        board4[6][2]='    '
        board6[6][2]='    '
        board3[6][3]='         '
        board4[6][3]='    '
        board6[6][3]='    '
        board3[6][4]='         '
        board4[6][4]='    '
        board6[6][4]='    '
        board3[6][5]='         '
        board4[6][5]='    '
        board6[6][5]='    '
        board3[6][6]='         '
        board4[6][6]='    '
        board6[6][6]='    '
        board3[6][7]='         '
        board4[6][7]='    '
        board6[6][7]='    '

        board[1][6]='m'
        board2[1][6]='m'

        board3[7][0]='         '
        board4[7][0]='    '
        board6[7][0]='    '
        board3[7][1]='         '
        board4[7][1]='    '
        board6[7][1]='    '
        board3[7][2]='         '
        board4[7][2]='    '
        board6[7][2]='    '
        board3[7][3]='         '
        board4[7][3]='    '
        board6[7][3]='    '
        board3[7][4]='         '
        board4[7][4]='    '
        board6[7][4]='    '
        board3[7][5]='         '
        board4[7][5]='    '
        board6[7][5]='    '
        board3[7][6]='         '
        board4[7][6]='    '
        board6[7][6]='    '
        board3[7][7]='         '
        board4[7][7]='    '
        board6[7][7]='    '

        

    elif board5=='A':
        for x in range(8):
            for y in range(8):
                board[x][y] = ' '
                board2[x][y] = ' '
        board3[0][0]='         '
        board4[0][0]='    '
        board6[0][0]='    '
        board3[0][1]='         '
        board4[0][1]='    '
        board6[0][1]='    '
        board3[0][2]='         '
        board4[0][2]='    '
        board6[0][2]='    '
        board3[0][3]='         '
        board4[0][3]='    '
        board6[0][3]='    '
        board3[0][4]='         '
        board4[0][4]='    '
        board6[0][4]='    '
        board3[0][5]='         '
        board4[0][5]='    '
        board6[0][5]='    '
        board3[0][6]='    mmmmm'
        board4[0][6]='    '
        board6[0][6]='mmmm'
        board3[0][7]='mmmmmmmmm'
        board4[0][7]='mmmm'
        board6[0][7]='mmmm'

        board[6][0]='m'
        board2[6][0]='m'
        board[7][0]='m'
        board2[7][0]='m'

        board3[1][0]='         '
        board4[1][0]='    '
        board6[1][0]='    '
        board3[1][1]='         '
        board4[1][1]='    '
        board6[1][1]='    '
        board3[1][2]='         '
        board4[1][2]='    '
        board6[1][2]='    '
        board3[1][3]='         '
        board4[1][3]='    '
        board6[1][3]='    '
        board3[1][4]='    mmmmm'
        board4[1][4]='    '
        board6[1][4]='mmmm'
        board3[1][5]='mmmmmmmmm'
        board4[1][5]='mmmm'
        board6[1][5]='mmmm'
        board3[1][6]='mmmmm    '
        board4[1][6]='mmmm'
        board6[1][6]='    '
        board3[1][7]='         '
        board4[1][7]='    '
        board6[1][7]='    '

        board[4][1]='m'
        board2[4][1]='m'
        board[5][1]='m'
        board2[5][1]='m'
        board[6][1]='m'
        board2[6][1]='m'

        board3[2][0]='         '
        board4[2][0]='    '
        board6[2][0]='    '
        board3[2][1]='         '
        board4[2][1]='    '
        board6[2][1]='    '
        board3[2][2]='    mmmmm'
        board4[2][2]='    '
        board6[2][2]='mmmm'
        board3[2][3]='mmmmmmmmm'
        board4[2][3]='mmmm'
        board6[2][3]='mmmm'
        board3[2][4]='mmmmmmmmm'
        board4[2][4]='mmmm'
        board6[2][4]='mmmm'
        board3[2][5]='         '
        board4[2][5]='    '
        board6[2][5]='    '
        board3[2][6]='         '
        board4[2][6]='    '
        board6[2][6]='    '
        board3[2][7]='         '
        board4[2][7]='    '
        board6[2][7]='    '

        board[2][2]='m'
        board2[2][2]='m'
        board[3][2]='m'
        board2[3][2]='m'
        board[4][2]='m'
        board2[4][2]='m'

        board3[3][0]='    mmmmm'
        board4[3][0]='    '
        board6[3][0]='mmmm'
        board3[3][1]='mmmmmmmmm'
        board4[3][1]='mmmm'
        board6[3][1]='mmmm'
        board3[3][2]='mmmmm    '
        board4[3][2]='mmmm'
        board6[3][2]='    '
        board3[3][3]='         '
        board4[3][3]='    '
        board6[3][3]='    '
        board3[3][4]='mmmmmmmmm'
        board4[3][4]='mmmm'
        board6[3][4]='mmmm'
        board3[3][5]='         '
        board4[3][5]='    '
        board6[3][5]='    '
        board3[3][6]='         '
        board4[3][6]='    '
        board6[3][6]='    '
        board3[3][7]='         '
        board4[3][7]='    '
        board6[3][7]='    '

        board[0][3]='m'
        board2[0][3]='m'
        board[1][3]='m'
        board2[1][3]='m'
        board[2][3]='m'
        board2[2][3]='m'
        board[4][3]='m'
        board2[4][3]='m'

        board3[4][0]='mmmmm    '
        board4[4][0]='mmmm'
        board6[4][0]='    '
        board3[4][1]='mmmmmmmmm'
        board4[4][1]='mmmm'
        board6[4][1]='mmmm'
        board3[4][2]='    mmmmm'
        board4[4][2]='    '
        board6[4][2]='mmmm'
        board3[4][3]='         '
        board4[4][3]='    '
        board6[4][3]='    '
        board3[4][4]='mmmmmmmmm'
        board4[4][4]='mmmm'
        board6[4][4]='mmmm'
        board3[4][5]='         '
        board4[4][5]='    '
        board6[4][5]='    '
        board3[4][6]='         '
        board4[4][6]='    '
        board6[4][6]='    '
        board3[4][7]='         '
        board4[4][7]='    '
        board6[4][7]='    '

        board[2][4]='m'
        board2[2][4]='m'
        board[1][4]='m'
        board2[1][4]='m'
        board[0][4]='m'
        board2[0][4]='m'
        board[4][4]='m'
        board2[4][4]='m'

        board3[5][0]='         '
        board4[5][0]='    '
        board6[5][0]='    '
        board3[5][1]='         '
        board4[5][1]='    '
        board6[5][1]='    '
        board3[5][2]='mmmmm    '
        board4[5][2]='mmmm'
        board6[5][2]='    '
        board3[5][3]='mmmmmmmmm'
        board4[5][3]='mmmm'
        board6[5][3]='mmmm'
        board3[5][4]='mmmmmmmmm'
        board4[5][4]='mmmm'
        board6[5][4]='mmmm'
        board3[5][5]='         '
        board4[5][5]='    '
        board6[5][5]='    '
        board3[5][6]='         '
        board4[5][6]='    '
        board6[5][6]='    '
        board3[5][7]='         '
        board4[5][7]='    '
        board6[5][7]='    '

        board[4][5]='m'
        board2[4][5]='m'
        board[3][5]='m'
        board2[3][5]='m'
        board[2][5]='m'
        board2[2][5]='m'
        
        board3[6][0]='         '
        board4[6][0]='    '
        board6[6][0]='    '
        board3[6][1]='         '
        board4[6][1]='    '
        board6[6][1]='    '
        board3[6][2]='         '
        board4[6][2]='    '
        board6[6][2]='    '
        board3[6][3]='         '
        board4[6][3]='    '
        board6[6][3]='    '
        board3[6][4]='mmmmm    '
        board4[6][4]='mmmm'
        board6[6][4]='    '
        board3[6][5]='mmmmmmmmm'
        board4[6][5]='mmmm'
        board6[6][5]='mmmm'
        board3[6][6]='    mmmmm'
        board4[6][6]='    '
        board6[6][6]='mmmm'
        board3[6][7]='         '
        board4[6][7]='    '
        board6[6][7]='    '

        board[6][6]='m'
        board2[6][6]='m'
        board[5][6]='m'
        board2[5][6]='m'
        board[4][6]='m'
        board2[4][6]='m'

        board3[7][0]='         '
        board4[7][0]='    '
        board6[7][0]='    '
        board3[7][1]='         '
        board4[7][1]='    '
        board6[7][1]='    '
        board3[7][2]='         '
        board4[7][2]='    '
        board6[7][2]='    '
        board3[7][3]='         '
        board4[7][3]='    '
        board6[7][3]='    '
        board3[7][4]='         '
        board4[7][4]='    '
        board6[7][4]='    '
        board3[7][5]='         '
        board4[7][5]='    '
        board6[7][5]='    '
        board3[7][6]='mmmmm    '
        board4[7][6]='mmmm'
        board6[7][6]='    '
        board3[7][7]='mmmmmmmmm'
        board4[7][7]='mmmm'
        board6[7][7]='mmmm'

        board[7][7]='m'
        board2[7][7]='m'
        board[6][7]='m'
        board2[6][7]='m'

    elif board5=='H':
        for x in range(8):
            for y in range(8):
                board[x][y] = ' '
                board2[x][y] = ' '
        board3[0][0]='         '
        board4[0][0]='    '
        board6[0][0]='    '
        board3[0][1]='         '
        board4[0][1]='    '
        board6[0][1]='    '
        board3[0][2]='         '
        board4[0][2]='    '
        board6[0][2]='    '
        board3[0][3]='         '
        board4[0][3]='    '
        board6[0][3]='    '
        board3[0][4]='         '
        board4[0][4]='    '
        board6[0][4]='    '
        board3[0][5]='         '
        board4[0][5]='    '
        board6[0][5]='    '
        board3[0][6]='         '
        board4[0][6]='    '
        board6[0][6]='    '
        board3[0][7]='         '
        board4[0][7]='    '
        board6[0][7]='    '

        

        board3[1][0]='mmmmmmmmm'
        board4[1][0]='mmmm'
        board6[1][0]='mmmm'
        board3[1][1]='mmmmmmmmm'
        board4[1][1]='mmmm'
        board6[1][1]='mmmm'
        board3[1][2]='mmmmmmmmm'
        board4[1][2]='mmmm'
        board6[1][2]='mmmm'
        board3[1][3]='mmmmmmmmm'
        board4[1][3]='mmmm'
        board6[1][3]='mmmm'
        board3[1][4]='mmmmmmmmm'
        board4[1][4]='mmmm'
        board6[1][4]='mmmm'
        board3[1][5]='mmmmmmmmm'
        board4[1][5]='mmmm'
        board6[1][5]='mmmm'
        board3[1][6]='mmmmmmmmm'
        board4[1][6]='mmmm'
        board6[1][6]='mmmm'
        board3[1][7]='mmmmmmmmm'
        board4[1][7]='mmmm'
        board6[1][7]='mmmm'

        board[0][1]='m'
        board2[0][1]='m'
        board[1][1]='m'
        board2[1][1]='m'
        board[2][1]='m'
        board2[2][1]='m'
        board[3][1]='m'
        board2[3][1]='m'
        board[4][1]='m'
        board2[4][1]='m'
        board[5][1]='m'
        board2[5][1]='m'
        board[6][1]='m'
        board2[6][1]='m'
        board[7][1]='m'
        board2[7][1]='m'

        board3[2][0]='         '
        board4[2][0]='    '
        board6[2][0]='    '
        board3[2][1]='         '
        board4[2][1]='    '
        board6[2][1]='    '
        board3[2][2]='         '
        board4[2][2]='    '
        board6[2][2]='    '
        board3[2][3]='         '
        board4[2][3]='mmmm'
        board6[2][3]='mmmm'
        board3[2][4]='mmmmmmmmm'
        board4[2][4]='    '
        board6[2][4]='    '
        board3[2][5]='         '
        board4[2][5]='    '
        board6[2][5]='    '
        board3[2][6]='         '
        board4[2][6]='    '
        board6[2][6]='    '
        board3[2][7]='         '
        board4[2][7]='    '
        board6[2][7]='    '

        board[3][2]='m'
        board2[3][2]='m'

        board3[3][0]='         '
        board4[3][0]='    '
        board6[3][0]='    '
        board3[3][1]='         '
        board4[3][1]='    '
        board6[3][1]='    '
        board3[3][2]='         '
        board4[3][2]='    '
        board6[3][2]='    '
        board3[3][3]='         '
        board4[3][3]='mmmm'
        board6[3][3]='mmmm'
        board3[3][4]='mmmmmmmmm'
        board4[3][4]='    '
        board6[3][4]='    '
        board3[3][5]='         '
        board4[3][5]='    '
        board6[3][5]='    '
        board3[3][6]='         '
        board4[3][6]='    '
        board6[3][6]='    '
        board3[3][7]='         '
        board4[3][7]='    '
        board6[3][7]='    '

        board[3][3]='m'
        board2[3][3]='m'

        board3[4][0]='         '
        board4[4][0]='    '
        board6[4][0]='    '
        board3[4][1]='         '
        board4[4][1]='    '
        board6[4][1]='    '
        board3[4][2]='         '
        board4[4][2]='    '
        board6[4][2]='    '
        board3[4][3]='         '
        board4[4][3]='mmmm'
        board6[4][3]='mmmm'
        board3[4][4]='mmmmmmmmm'
        board4[4][4]='    '
        board6[4][4]='    '
        board3[4][5]='         '
        board4[4][5]='    '
        board6[4][5]='    '
        board3[4][6]='         '
        board4[4][6]='    '
        board6[4][6]='    '
        board3[4][7]='         '
        board4[4][7]='    '
        board6[4][7]='    '

        board[3][4]='m'
        board2[3][4]='m'

        board3[5][0]='         '
        board4[5][0]='    '
        board6[5][0]='    '
        board3[5][1]='         '
        board4[5][1]='    '
        board6[5][1]='    '
        board3[5][2]='         '
        board4[5][2]='    '
        board6[5][2]='    '
        board3[5][3]='         '
        board4[5][3]='mmmm'
        board6[5][3]='mmmm'
        board3[5][4]='mmmmmmmmm'
        board4[5][4]='    '
        board6[5][4]='    '
        board3[5][5]='         '
        board4[5][5]='    '
        board6[5][5]='    '
        board3[5][6]='         '
        board4[5][6]='    '
        board6[5][6]='    '
        board3[5][7]='         '
        board4[5][7]='    '
        board6[5][7]='    '

        board[3][5]='m'
        board2[3][5]='m'

        board3[6][0]='mmmmmmmmm'
        board4[6][0]='mmmm'
        board6[6][0]='mmmm'
        board3[6][1]='mmmmmmmmm'
        board4[6][1]='mmmm'
        board6[6][1]='mmmm'
        board3[6][2]='mmmmmmmmm'
        board4[6][2]='mmmm'
        board6[6][2]='mmmm'
        board3[6][3]='mmmmmmmmm'
        board4[6][3]='mmmm'
        board6[6][3]='mmmm'
        board3[6][4]='mmmmmmmmm'
        board4[6][4]='mmmm'
        board6[6][4]='mmmm'
        board3[6][5]='mmmmmmmmm'
        board4[6][5]='mmmm'
        board6[6][5]='mmmm'
        board3[6][6]='mmmmmmmmm'
        board4[6][6]='mmmm'
        board6[6][6]='mmmm'
        board3[6][7]='mmmmmmmmm'
        board4[6][7]='mmmm'
        board6[6][7]='mmmm'

        board[0][6]='m'
        board2[0][6]='m'
        board[1][6]='m'
        board2[1][6]='m'
        board[2][6]='m'
        board2[2][6]='m'
        board[3][6]='m'
        board2[3][6]='m'
        board[4][6]='m'
        board2[4][6]='m'
        board[5][6]='m'
        board2[5][6]='m'
        board[6][6]='m'
        board2[6][6]='m'
        board[7][6]='m'
        board2[7][6]='m'
        
        board3[7][0]='         '
        board4[7][0]='    '
        board6[7][0]='    '
        board3[7][1]='         '
        board4[7][1]='    '
        board6[7][1]='    '
        board3[7][2]='         '
        board4[7][2]='    '
        board6[7][2]='    '
        board3[7][3]='         '
        board4[7][3]='    '
        board6[7][3]='    '
        board3[7][4]='         '
        board4[7][4]='    '
        board6[7][4]='    '
        board3[7][5]='         '
        board4[7][5]='    '
        board6[7][5]='    '
        board3[7][6]='         '
        board4[7][6]='    '
        board6[7][6]='    '
        board3[7][7]='         '
        board4[7][7]='    '
        board6[7][7]='    '

    elif board5=='E':
        for x in range(8):
            for y in range(8):
                board[x][y] = ' '
                board2[x][y] = ' '
        board3[0][0]='         '
        board4[0][0]='    '
        board6[0][0]='    '
        board3[0][1]='         '
        board4[0][1]='    '
        board6[0][1]='    '
        board3[0][2]='         '
        board4[0][2]='    '
        board6[0][2]='    '
        board3[0][3]='         '
        board4[0][3]='    '
        board6[0][3]='    '
        board3[0][4]='         '
        board4[0][4]='    '
        board6[0][4]='    '
        board3[0][5]='         '
        board4[0][5]='    '
        board6[0][5]='    '
        board3[0][6]='         '
        board4[0][6]='    '
        board6[0][6]='    '
        board3[0][7]='         '
        board4[0][7]='    '
        board6[0][7]='    '

        board3[1][0]='mmmmmmmmm'
        board4[1][0]='mmmm'
        board6[1][0]='mmmm'
        board3[1][1]='mmmmmmmmm'
        board4[1][1]='mmmm'
        board6[1][1]='mmmm'
        board3[1][2]='mmmmmmmmm'
        board4[1][2]='mmmm'
        board6[1][2]='mmmm'
        board3[1][3]='mmmmmmmmm'
        board4[1][3]='mmmm'
        board6[1][3]='mmmm'
        board3[1][4]='mmmmmmmmm'
        board4[1][4]='mmmm'
        board6[1][4]='mmmm'
        board3[1][5]='mmmmmmmmm'
        board4[1][5]='mmmm'
        board6[1][5]='mmmm'
        board3[1][6]='mmmmmmmmm'
        board4[1][6]='mmmm'
        board6[1][6]='mmmm'
        board3[1][7]='mmmmmmmmm'
        board4[1][7]='mmmm'
        board6[1][7]='mmmm'

        board[0][1]='m'
        board2[0][1]='m'
        board[1][1]='m'
        board2[1][1]='m'
        board[2][1]='m'
        board2[2][1]='m'
        board[3][1]='m'
        board2[3][1]='m'
        board[4][1]='m'
        board2[4][1]='m'
        board[5][1]='m'
        board2[5][1]='m'
        board[6][1]='m'
        board2[6][1]='m'
        board[7][1]='m'
        board2[7][1]='m'

        board3[2][0]='mmmmmmmmm'
        board4[2][0]='mmmm'
        board6[2][0]='mmmm'
        board3[2][1]='         '
        board4[2][1]='    '
        board6[2][1]='    '
        board3[2][2]='         '
        board4[2][2]='    '
        board6[2][2]='    '
        board3[2][3]='         '
        board4[2][3]='mmmm'
        board6[2][3]='mmmm'
        board3[2][4]='mmmmmmmmm'
        board4[2][4]='    '
        board6[2][4]='    '
        board3[2][5]='         '
        board4[2][5]='    '
        board6[2][5]='    '
        board3[2][6]='         '
        board4[2][6]='    '
        board6[2][6]='    '
        board3[2][7]='mmmmmmmmm'
        board4[2][7]='mmmm'
        board6[2][7]='mmmm'

        board[0][2]='m'
        board2[0][2]='m'
        board[3][2]='m'
        board2[3][2]='m'
        board[7][2]='m'
        board2[7][2]='m'

        board3[3][0]='mmmmmmmmm'
        board4[3][0]='mmmm'
        board6[3][0]='mmmm'
        board3[3][1]='         '
        board4[3][1]='    '
        board6[3][1]='    '
        board3[3][2]='         '
        board4[3][2]='    '
        board6[3][2]='    '
        board3[3][3]='         '
        board4[3][3]='mmmm'
        board6[3][3]='mmmm'
        board3[3][4]='mmmmmmmmm'
        board4[3][4]='    '
        board6[3][4]='    '
        board3[3][5]='         '
        board4[3][5]='    '
        board6[3][5]='    '
        board3[3][6]='         '
        board4[3][6]='    '
        board6[3][6]='    '
        board3[3][7]='mmmmmmmmm'
        board4[3][7]='mmmm'
        board6[3][7]='mmmm'

        board[0][3]='m'
        board2[0][3]='m'
        board[3][3]='m'
        board2[3][3]='m'
        board[7][3]='m'
        board2[7][3]='m'

        board3[4][0]='mmmmmmmmm'
        board4[4][0]='mmmm'
        board6[4][0]='mmmm'
        board3[4][1]='         '
        board4[4][1]='    '
        board6[4][1]='    '
        board3[4][2]='         '
        board4[4][2]='    '
        board6[4][2]='    '
        board3[4][3]='         '
        board4[4][3]='mmmm'
        board6[4][3]='mmmm'
        board3[4][4]='mmmmmmmmm'
        board4[4][4]='    '
        board6[4][4]='    '
        board3[4][5]='         '
        board4[4][5]='    '
        board6[4][5]='    '
        board3[4][6]='         '
        board4[4][6]='    '
        board6[4][6]='    '
        board3[4][7]='mmmmmmmmm'
        board4[4][7]='mmmm'
        board6[4][7]='mmmm'

        board[0][4]='m'
        board2[0][4]='m'
        board[3][4]='m'
        board2[3][4]='m'
        board[7][4]='m'
        board2[7][4]='m'

        board3[5][0]='mmmmmmmmm'
        board4[5][0]='mmmm'
        board6[5][0]='mmmm'
        board3[5][1]='         '
        board4[5][1]='    '
        board6[5][1]='    '
        board3[5][2]='         '
        board4[5][2]='    '
        board6[5][2]='    '
        board3[5][3]='         '
        board4[5][3]='    '
        board6[5][3]='    '
        board3[5][4]='         '
        board4[5][4]='    '
        board6[5][4]='    '
        board3[5][5]='         '
        board4[5][5]='    '
        board6[5][5]='    '
        board3[5][6]='         '
        board4[5][6]='    '
        board6[5][6]='    '
        board3[5][7]='mmmmmmmmm'
        board4[5][7]='mmmm'
        board6[5][7]='mmmm'

        board[0][5]='m'
        board2[0][5]='m'
        board[7][5]='m'
        board2[7][5]='m'
        
        board3[6][0]='         '
        board4[6][0]='    '
        board6[6][0]='    '
        board3[6][1]='         '
        board4[6][1]='    '
        board6[6][1]='    '
        board3[6][2]='         '
        board4[6][2]='    '
        board6[6][2]='    '
        board3[6][3]='         '
        board4[6][3]='    '
        board6[6][3]='    '
        board3[6][4]='         '
        board4[6][4]='    '
        board6[6][4]='    '
        board3[6][5]='         '
        board4[6][5]='    '
        board6[6][5]='    '
        board3[6][6]='         '
        board4[6][6]='    '
        board6[6][6]='    '
        board3[6][7]='         '
        board4[6][7]='    '
        board6[6][7]='    '

        

        board3[7][0]='         '
        board4[7][0]='    '
        board6[7][0]='    '
        board3[7][1]='         '
        board4[7][1]='    '
        board6[7][1]='    '
        board3[7][2]='         '
        board4[7][2]='    '
        board6[7][2]='    '
        board3[7][3]='         '
        board4[7][3]='    '
        board6[7][3]='    '
        board3[7][4]='         '
        board4[7][4]='    '
        board6[7][4]='    '
        board3[7][5]='         '
        board4[7][5]='    '
        board6[7][5]='    '
        board3[7][6]='         '
        board4[7][6]='    '
        board6[7][6]='    '
        board3[7][7]='         '
        board4[7][7]='    '
        board6[7][7]='    '

    elif board5=='L':
        for x in range(8):
            for y in range(8):
                board[x][y] = ' '
                board2[x][y] = ' '
        board3[0][0]='         '
        board4[0][0]='    '
        board6[0][0]='    '
        board3[0][1]='         '
        board4[0][1]='    '
        board6[0][1]='    '
        board3[0][2]='         '
        board4[0][2]='    '
        board6[0][2]='    '
        board3[0][3]='         '
        board4[0][3]='    '
        board6[0][3]='    '
        board3[0][4]='         '
        board4[0][4]='    '
        board6[0][4]='    '
        board3[0][5]='         '
        board4[0][5]='    '
        board6[0][5]='    '
        board3[0][6]='         '
        board4[0][6]='    '
        board6[0][6]='    '
        board3[0][7]='         '
        board4[0][7]='    '
        board6[0][7]='    '

        board3[1][0]='mmmmmmmmm'
        board4[1][0]='mmmm'
        board6[1][0]='mmmm'
        board3[1][1]='mmmmmmmmm'
        board4[1][1]='mmmm'
        board6[1][1]='mmmm'
        board3[1][2]='mmmmmmmmm'
        board4[1][2]='mmmm'
        board6[1][2]='mmmm'
        board3[1][3]='mmmmmmmmm'
        board4[1][3]='mmmm'
        board6[1][3]='mmmm'
        board3[1][4]='mmmmmmmmm'
        board4[1][4]='mmmm'
        board6[1][4]='mmmm'
        board3[1][5]='mmmmmmmmm'
        board4[1][5]='mmmm'
        board6[1][5]='mmmm'
        board3[1][6]='mmmmmmmmm'
        board4[1][6]='mmmm'
        board6[1][6]='mmmm'
        board3[1][7]='mmmmmmmmm'
        board4[1][7]='mmmm'
        board6[1][7]='mmmm'

        board[0][1]='m'
        board2[0][1]='m'
        board[1][1]='m'
        board2[1][1]='m'
        board[2][1]='m'
        board2[2][1]='m'
        board[3][1]='m'
        board2[3][1]='m'
        board[4][1]='m'
        board2[4][1]='m'
        board[5][1]='m'
        board2[5][1]='m'
        board[6][1]='m'
        board2[6][1]='m'
        board[7][1]='m'
        board2[7][1]='m'

        board3[2][0]='         '
        board4[2][0]='    '
        board6[2][0]='    '
        board3[2][1]='         '
        board4[2][1]='    '
        board6[2][1]='    '
        board3[2][2]='         '
        board4[2][2]='    '
        board6[2][2]='    '
        board3[2][3]='         '
        board4[2][3]='    '
        board6[2][3]='    '
        board3[2][4]='         '
        board4[2][4]='    '
        board6[2][4]='    '
        board3[2][5]='         '
        board4[2][5]='    '
        board6[2][5]='    '
        board3[2][6]='         '
        board4[2][6]='    '
        board6[2][6]='    '
        board3[2][7]='mmmmmmmmm'
        board4[2][7]='mmmm'
        board6[2][7]='mmmm'

        board[7][2]='m'
        board2[7][2]='m'

        board3[3][0]='         '
        board4[3][0]='    '
        board6[3][0]='    '
        board3[3][1]='         '
        board4[3][1]='    '
        board6[3][1]='    '
        board3[3][2]='         '
        board4[3][2]='    '
        board6[3][2]='    '
        board3[3][3]='         '
        board4[3][3]='    '
        board6[3][3]='    '
        board3[3][4]='         '
        board4[3][4]='    '
        board6[3][4]='    '
        board3[3][5]='         '
        board4[3][5]='    '
        board6[3][5]='    '
        board3[3][6]='         '
        board4[3][6]='    '
        board6[3][6]='    '
        board3[3][7]='mmmmmmmmm'
        board4[3][7]='mmmm'
        board6[3][7]='mmmm'

        board[7][3]='m'
        board2[7][3]='m'

        board3[4][0]='         '
        board4[4][0]='    '
        board6[4][0]='    '
        board3[4][1]='         '
        board4[4][1]='    '
        board6[4][1]='    '
        board3[4][2]='         '
        board4[4][2]='    '
        board6[4][2]='    '
        board3[4][3]='         '
        board4[4][3]='    '
        board6[4][3]='    '
        board3[4][4]='         '
        board4[4][4]='    '
        board6[4][4]='    '
        board3[4][5]='         '
        board4[4][5]='    '
        board6[4][5]='    '
        board3[4][6]='         '
        board4[4][6]='    '
        board6[4][6]='    '
        board3[4][7]='mmmmmmmmm'
        board4[4][7]='mmmm'
        board6[4][7]='mmmm'

        board[7][4]='m'
        board2[7][4]='m'

        board3[5][0]='         '
        board4[5][0]='    '
        board6[5][0]='    '
        board3[5][1]='         '
        board4[5][1]='    '
        board6[5][1]='    '
        board3[5][2]='         '
        board4[5][2]='    '
        board6[5][2]='    '
        board3[5][3]='         '
        board4[5][3]='    '
        board6[5][3]='    '
        board3[5][4]='         '
        board4[5][4]='    '
        board6[5][4]='    '
        board3[5][5]='         '
        board4[5][5]='    '
        board6[5][5]='    '
        board3[5][6]='         '
        board4[5][6]='    '
        board6[5][6]='    '
        board3[5][7]='mmmmmmmmm'
        board4[5][7]='mmmm'
        board6[5][7]='mmmm'

        board[7][5]='m'
        board2[7][5]='m'
        
        board3[6][0]='         '
        board4[6][0]='    '
        board6[6][0]='    '
        board3[6][1]='         '
        board4[6][1]='    '
        board6[6][1]='    '
        board3[6][2]='         '
        board4[6][2]='    '
        board6[6][2]='    '
        board3[6][3]='         '
        board4[6][3]='    '
        board6[6][3]='    '
        board3[6][4]='         '
        board4[6][4]='    '
        board6[6][4]='    '
        board3[6][5]='         '
        board4[6][5]='    '
        board6[6][5]='    '
        board3[6][6]='         '
        board4[6][6]='    '
        board6[6][6]='    '
        board3[6][7]='         '
        board4[6][7]='    '
        board6[6][7]='    '

        

        board3[7][0]='         '
        board4[7][0]='    '
        board6[7][0]='    '
        board3[7][1]='         '
        board4[7][1]='    '
        board6[7][1]='    '
        board3[7][2]='         '
        board4[7][2]='    '
        board6[7][2]='    '
        board3[7][3]='         '
        board4[7][3]='    '
        board6[7][3]='    '
        board3[7][4]='         '
        board4[7][4]='    '
        board6[7][4]='    '
        board3[7][5]='         '
        board4[7][5]='    '
        board6[7][5]='    '
        board3[7][6]='         '
        board4[7][6]='    '
        board6[7][6]='    '
        board3[7][7]='         '
        board4[7][7]='    '
        board6[7][7]='    '

    elif board5=='O':
        for x in range(8):
            for y in range(8):
                board[x][y] = ' '
                board2[x][y] = ' '
        board3[0][0]='         '
        board4[0][0]='    '
        board6[0][0]='    '
        board3[0][1]='         '
        board4[0][1]='    '
        board6[0][1]='    '
        board3[0][2]='         '
        board4[0][2]='    '
        board6[0][2]='    '
        board3[0][3]='     mmmm'
        board4[0][3]='    '
        board6[0][3]='mmmm'
        board3[0][4]='     mmmm'
        board4[0][4]='    '
        board6[0][4]='mmmm'
        board3[0][5]='         '
        board4[0][5]='    '
        board6[0][5]='    '
        board3[0][6]='         '
        board4[0][6]='    '
        board6[0][6]='    '
        board3[0][7]='         '
        board4[0][7]='    '
        board6[0][7]='    '

        

        board3[1][0]='         '
        board4[1][0]='    '
        board6[1][0]='    '
        board3[1][1]='    mmmmm'
        board4[1][1]='    '
        board6[1][1]='mmmm'
        board3[1][2]='mmmmmmmmm'
        board4[1][2]='mmmm'
        board6[1][2]='mmmm'
        board3[1][3]='mmmmm    '
        board4[1][3]='mmmm'
        board6[1][3]='    '
        board3[1][4]='mmmmm    '
        board4[1][4]='mmmm'
        board6[1][4]='    '
        board3[1][5]='mmmmmmmmm'
        board4[1][5]='mmmm'
        board6[1][5]='mmmm'
        board3[1][6]='    mmmmm'
        board4[1][6]='    '
        board6[1][6]='mmmm'
        board3[1][7]='         '
        board4[1][7]='    '
        board6[1][7]='    '

        board[2][1]='m'
        board2[2][1]='m'
        board[3][1]='m'
        board2[3][1]='m'
        board[4][1]='m'
        board2[4][1]='m'
        board[5][1]='m'
        board2[5][1]='m'
        board[1][1]='m'
        board2[1][1]='m'
        board[6][1]='m'
        board2[6][1]='m'

        board3[2][0]='mmmmmmmmm'
        board4[2][0]='mmmm'
        board6[2][0]='mmmm'
        board3[2][1]='mmmmm    '
        board4[2][1]='mmmm'
        board6[2][1]='    '
        board3[2][2]='         '
        board4[2][2]='    '
        board6[2][2]='    '
        board3[2][3]='         '
        board4[2][3]='    '
        board6[2][3]='    '
        board3[2][4]='         '
        board4[2][4]='    '
        board6[2][4]='    '
        board3[2][5]='         '
        board4[2][5]='    '
        board6[2][5]='    '
        board3[2][6]='mmmmm    '
        board4[2][6]='mmmm'
        board6[2][6]='    '
        board3[2][7]='mmmmmmmmm'
        board4[2][7]='mmmm'
        board6[2][7]='mmmm'

        board[1][2]='m'
        board2[1][2]='m'
        board[6][2]='m'
        board2[6][2]='m'
        board[0][2]='m'
        board2[0][2]='m'
        board[7][2]='m'
        board2[7][2]='m'

        board3[3][0]='mmmmmmmmm'
        board4[3][0]='    '
        board6[3][0]='    '
        board3[3][1]='         '
        board4[3][1]='    '
        board6[3][1]='    '
        board3[3][2]='         '
        board4[3][2]='    '
        board6[3][2]='    '
        board3[3][3]='         '
        board4[3][3]='    '
        board6[3][3]='    '
        board3[3][4]='         '
        board4[3][4]='    '
        board6[3][4]='    '
        board3[3][5]='         '
        board4[3][5]='    '
        board6[3][5]='    '
        board3[3][6]='         '
        board4[3][6]='    '
        board6[3][6]='    '
        board3[3][7]='         '
        board4[3][7]='mmmm'
        board6[3][7]='mmmm'

        board[7][3]='m'
        board2[7][3]='m'

        board3[4][0]='mmmmmmmmm'
        board4[4][0]='    '
        board6[4][0]='    '
        board3[4][1]='         '
        board4[4][1]='    '
        board6[4][1]='    '
        board3[4][2]='         '
        board4[4][2]='    '
        board6[4][2]='    '
        board3[4][3]='         '
        board4[4][3]='    '
        board6[4][3]='    '
        board3[4][4]='         '
        board4[4][4]='    '
        board6[4][4]='    '
        board3[4][5]='         '
        board4[4][5]='    '
        board6[4][5]='    '
        board3[4][6]='         '
        board4[4][6]='    '
        board6[4][6]='    '
        board3[4][7]='         '
        board4[4][7]='mmmm'
        board6[4][7]='mmmm'

        board[7][4]='m'
        board2[7][4]='m'

        board3[5][0]='mmmmmmmmm'
        board4[5][0]='mmmm'
        board6[5][0]='mmmm'
        board3[5][1]='    mmmmm'
        board4[5][1]='    '
        board6[5][1]='mmmm'
        board3[5][2]='         '
        board4[5][2]='    '
        board6[5][2]='    '
        board3[5][3]='         '
        board4[5][3]='    '
        board6[5][3]='    '
        board3[5][4]='         '
        board4[5][4]='    '
        board6[5][4]='    '
        board3[5][5]='         '
        board4[5][5]='    '
        board6[5][5]='    '
        board3[5][6]='    mmmmm'
        board4[5][6]='    '
        board6[5][6]='mmmm'
        board3[5][7]='mmmmmmmmm'
        board4[5][7]='mmmm'
        board6[5][7]='mmmm'

        board[1][5]='m'
        board2[1][5]='m'
        board[6][5]='m'
        board2[6][5]='m'
        board[0][5]='m'
        board2[0][5]='m'
        board[7][5]='m'
        board2[7][5]='m'
        
        board3[6][0]='         '
        board4[6][0]='    '
        board6[6][0]='    '
        board3[6][1]='mmmmm    '
        board4[6][1]='mmmm'
        board6[6][1]='    '
        board3[6][2]='mmmmmmmmm'
        board4[6][2]='mmmm'
        board6[6][2]='mmmm'
        board3[6][3]='    mmmmm'
        board4[6][3]='    '
        board6[6][3]='mmmm'
        board3[6][4]='    mmmmm'
        board4[6][4]='    '
        board6[6][4]='mmmm'
        board3[6][5]='mmmmmmmmm'
        board4[6][5]='mmmm'
        board6[6][5]='mmmm'
        board3[6][6]='mmmmm    '
        board4[6][6]='mmmm'
        board6[6][6]='    '
        board3[6][7]='         '
        board4[6][7]='    '
        board6[6][7]='    '

        board[2][6]='m'
        board2[2][6]='m'
        board[3][6]='m'
        board2[3][6]='m'
        board[4][6]='m'
        board2[4][6]='m'
        board[5][6]='m'
        board2[5][6]='m'
        board[1][6]='m'
        board2[1][6]='m'
        board[6][6]='m'
        board2[6][6]='m'

        board3[7][0]='         '
        board4[7][0]='    '
        board6[7][0]='    '
        board3[7][1]='         '
        board4[7][1]='    '
        board6[7][1]='    '
        board3[7][2]='         '
        board4[7][2]='    '
        board6[7][2]='    '
        board3[7][3]='mmmm     '
        board4[7][3]='mmmm'
        board6[7][3]='    '
        board3[7][4]='mmmm     '
        board4[7][4]='mmmm'
        board6[7][4]='    '
        board3[7][5]='         '
        board4[7][5]='    '
        board6[7][5]='    '
        board3[7][6]='         '
        board4[7][6]='    '
        board6[7][6]='    '
        board3[7][7]='         '
        board4[7][7]='    '
        board6[7][7]='    '

    elif board5=='B':
        for x in range(8):
            for y in range(8):
                board[x][y] = ' '
                board2[x][y] = ' '
        board3[0][0]='         '
        board4[0][0]='    '
        board6[0][0]='    '
        board3[0][1]='         '
        board4[0][1]='    '
        board6[0][1]='    '
        board3[0][2]='         '
        board4[0][2]='    '
        board6[0][2]='    '
        board3[0][3]='         '
        board4[0][3]='    '
        board6[0][3]='    '
        board3[0][4]='         '
        board4[0][4]='    '
        board6[0][4]='    '
        board3[0][5]='         '
        board4[0][5]='    '
        board6[0][5]='    '
        board3[0][6]='         '
        board4[0][6]='    '
        board6[0][6]='    '
        board3[0][7]='         '
        board4[0][7]='    '
        board6[0][7]='    '

        board3[1][0]='mmmmmmmmm'
        board4[1][0]='mmmm'
        board6[1][0]='mmmm'
        board3[1][1]='mmmmmmmmm'
        board4[1][1]='mmmm'
        board6[1][1]='mmmm'
        board3[1][2]='mmmmmmmmm'
        board4[1][2]='mmmm'
        board6[1][2]='mmmm'
        board3[1][3]='mmmmmmmmm'
        board4[1][3]='mmmm'
        board6[1][3]='mmmm'
        board3[1][4]='mmmmmmmmm'
        board4[1][4]='mmmm'
        board6[1][4]='mmmm'
        board3[1][5]='mmmmmmmmm'
        board4[1][5]='mmmm'
        board6[1][5]='mmmm'
        board3[1][6]='mmmmmmmmm'
        board4[1][6]='mmmm'
        board6[1][6]='mmmm'
        board3[1][7]='mmmmmmmmm'
        board4[1][7]='mmmm'
        board6[1][7]='mmmm'

        board[0][1]='m'
        board2[0][1]='m'
        board[1][1]='m'
        board2[1][1]='m'
        board[2][1]='m'
        board2[2][1]='m'
        board[3][1]='m'
        board2[3][1]='m'
        board[4][1]='m'
        board2[4][1]='m'
        board[5][1]='m'
        board2[5][1]='m'
        board[6][1]='m'
        board2[6][1]='m'
        board[7][1]='m'
        board2[7][1]='m'

        board3[2][0]='mmmmmmmmm'
        board4[2][0]='mmmm'
        board6[2][0]='mmmm'
        board3[2][1]='         '
        board4[2][1]='    '
        board6[2][1]='    '
        board3[2][2]='         '
        board4[2][2]='    '
        board6[2][2]='    '
        board3[2][3]='     mmmm'
        board4[2][3]='mmmm'
        board6[2][3]='mmmm'
        board3[2][4]='mmmmmmmmm'
        board4[2][4]='    '
        board6[2][4]='mmmm'
        board3[2][5]='         '
        board4[2][5]='    '
        board6[2][5]='    '
        board3[2][6]='         '
        board4[2][6]='    '
        board6[2][6]='    '
        board3[2][7]='mmmmmmmmm'
        board4[2][7]='mmmm'
        board6[2][7]='mmmm'

        board[3][2]='m'
        board2[3][2]='m'
        board[7][2]='m'
        board2[7][2]='m'
        board[0][2]='m'
        board2[0][2]='m'
        

        board3[3][0]='mmmmm    '
        board4[3][0]='mmmm'
        board6[3][0]='    '
        board3[3][1]='mmmmmmmmm'
        board4[3][1]='mmmm'
        board6[3][1]='mmmm'
        board3[3][2]='    mmmmm'
        board4[3][2]='    '
        board6[3][2]='mmmm'
        board3[3][3]='mmmmmmmmm'
        board4[3][3]='mmmm'
        board6[3][3]='mmmm'
        board3[3][4]='mmmmmmmmm'
        board4[3][4]='mmmm'
        board6[3][4]='mmmm'
        board3[3][5]='    mmmmm'
        board4[3][5]='    '
        board6[3][5]='mmmm'
        board3[3][6]='mmmmmmmmm'
        board4[3][6]='mmmm'
        board6[3][6]='mmmm'
        board3[3][7]='mmmmm    '
        board4[3][7]='mmmm'
        board6[3][7]='    '

        board[0][3]='m'
        board2[0][3]='m'
        board[1][3]='m'
        board2[1][3]='m'
        board[6][3]='m'
        board2[6][3]='m'
        board[7][3]='m'
        board2[7][3]='m'
        board[3][3]='m'
        board2[3][3]='m'
        board[4][3]='m'
        board2[4][3]='m'
        board[2][3]='m'
        board2[2][3]='m'
        board[5][3]='m'
        board2[5][3]='m'

        board3[4][1]='mmmmm    '
        board4[4][1]='mmmm'
        board6[4][1]='    '
        board3[4][2]='mmmmmmmmm'
        board4[4][2]='mmmm'
        board6[4][2]='mmmm'
        board3[4][0]='         '
        board4[4][0]='    '
        board6[4][0]='    '
        board3[4][3]='mmmmm    '
        board4[4][3]='mmmm'
        board6[4][3]='    '
        board3[4][4]='mmmmm    '
        board4[4][4]='mmmm'
        board6[4][4]='    '
        board3[4][7]='         '
        board4[4][7]='    '
        board6[4][7]='    '
        board3[4][5]='mmmmmmmmm'
        board4[4][5]='mmmm'
        board6[4][5]='mmmm'
        board3[4][6]='mmmmm    '
        board4[4][6]='mmmm'
        board6[4][6]='    '

        board[2][4]='m'
        board2[2][4]='m'
        board[1][4]='m'
        board2[1][4]='m'
        board[6][4]='m'
        board2[6][4]='m'
        board[5][4]='m'
        board2[5][4]='m'
        board[3][4]='m'
        board2[3][4]='m'
        board[4][4]='m'
        board2[4][4]='m'

        board3[5][0]='         '
        board4[5][0]='    '
        board6[5][0]='    '
        board3[5][1]='         '
        board4[5][1]='    '
        board6[5][1]='    '
        board3[5][2]='         '
        board4[5][2]='    '
        board6[5][2]='    '
        board3[5][3]='         '
        board4[5][3]='    '
        board6[5][3]='    '
        board3[5][4]='         '
        board4[5][4]='    '
        board6[5][4]='    '
        board3[5][5]='         '
        board4[5][5]='    '
        board6[5][5]='    '
        board3[5][6]='         '
        board4[5][6]='    '
        board6[5][6]='    '
        board3[5][7]='         '
        board4[5][7]='    '
        board6[5][7]='    '

        
        
        board3[6][0]='         '
        board4[6][0]='    '
        board6[6][0]='    '
        board3[6][1]='         '
        board4[6][1]='    '
        board6[6][1]='    '
        board3[6][2]='         '
        board4[6][2]='    '
        board6[6][2]='    '
        board3[6][3]='         '
        board4[6][3]='    '
        board6[6][3]='    '
        board3[6][4]='         '
        board4[6][4]='    '
        board6[6][4]='    '
        board3[6][5]='         '
        board4[6][5]='    '
        board6[6][5]='    '
        board3[6][6]='         '
        board4[6][6]='    '
        board6[6][6]='    '
        board3[6][7]='         '
        board4[6][7]='    '
        board6[6][7]='    '

        

        board3[7][0]='         '
        board4[7][0]='    '
        board6[7][0]='    '
        board3[7][1]='         '
        board4[7][1]='    '
        board6[7][1]='    '
        board3[7][2]='         '
        board4[7][2]='    '
        board6[7][2]='    '
        board3[7][3]='         '
        board4[7][3]='    '
        board6[7][3]='    '
        board3[7][4]='         '
        board4[7][4]='    '
        board6[7][4]='    '
        board3[7][5]='         '
        board4[7][5]='    '
        board6[7][5]='    '
        board3[7][6]='         '
        board4[7][6]='    '
        board6[7][6]='    '
        board3[7][7]='         '
        board4[7][7]='    '
        board6[7][7]='    '

    elif board5=='F':
        for x in range(8):
            for y in range(8):
                board[x][y] = ' '
                board2[x][y] = ' '
        board3[0][0]='         '
        board4[0][0]='    '
        board6[0][0]='    '
        board3[0][1]='         '
        board4[0][1]='    '
        board6[0][1]='    '
        board3[0][2]='         '
        board4[0][2]='    '
        board6[0][2]='    '
        board3[0][3]='         '
        board4[0][3]='    '
        board6[0][3]='    '
        board3[0][4]='         '
        board4[0][4]='    '
        board6[0][4]='    '
        board3[0][5]='         '
        board4[0][5]='    '
        board6[0][5]='    '
        board3[0][6]='         '
        board4[0][6]='    '
        board6[0][6]='    '
        board3[0][7]='         '
        board4[0][7]='    '
        board6[0][7]='    '

        board3[1][0]='mmmmmmmmm'
        board4[1][0]='mmmm'
        board6[1][0]='mmmm'
        board3[1][1]='mmmmmmmmm'
        board4[1][1]='mmmm'
        board6[1][1]='mmmm'
        board3[1][2]='mmmmmmmmm'
        board4[1][2]='mmmm'
        board6[1][2]='mmmm'
        board3[1][3]='mmmmmmmmm'
        board4[1][3]='mmmm'
        board6[1][3]='mmmm'
        board3[1][4]='mmmmmmmmm'
        board4[1][4]='mmmm'
        board6[1][4]='mmmm'
        board3[1][5]='mmmmmmmmm'
        board4[1][5]='mmmm'
        board6[1][5]='mmmm'
        board3[1][6]='mmmmmmmmm'
        board4[1][6]='mmmm'
        board6[1][6]='mmmm'
        board3[1][7]='mmmmmmmmm'
        board4[1][7]='mmmm'
        board6[1][7]='mmmm'

        board[0][1]='m'
        board2[0][1]='m'
        board[1][1]='m'
        board2[1][1]='m'
        board[2][1]='m'
        board2[2][1]='m'
        board[3][1]='m'
        board2[3][1]='m'
        board[4][1]='m'
        board2[4][1]='m'
        board[5][1]='m'
        board2[5][1]='m'
        board[6][1]='m'
        board2[6][1]='m'
        board[7][1]='m'
        board2[7][1]='m'

        board3[2][0]='mmmmmmmmm'
        board4[2][0]='mmmm'
        board6[2][0]='mmmm'
        board3[2][1]='         '
        board4[2][1]='    '
        board6[2][1]='    '
        board3[2][2]='         '
        board4[2][2]='    '
        board6[2][2]='    '
        board3[2][3]='         '
        board4[2][3]='mmmm'
        board6[2][3]='mmmm'
        board3[2][4]='mmmmmmmmm'
        board4[2][4]='    '
        board6[2][4]='    '
        board3[2][5]='         '
        board4[2][5]='    '
        board6[2][5]='    '
        board3[2][6]='         '
        board4[2][6]='    '
        board6[2][6]='    '
        board3[2][7]='         '
        board4[2][7]='    '
        board6[2][7]='    '

        board[0][2]='m'
        board2[0][2]='m'
        board[3][2]='m'
        board2[3][2]='m'

        board3[3][0]='mmmmmmmmm'
        board4[3][0]='mmmm'
        board6[3][0]='mmmm'
        board3[3][1]='         '
        board4[3][1]='    '
        board6[3][1]='    '
        board3[3][2]='         '
        board4[3][2]='    '
        board6[3][2]='    '
        board3[3][3]='         '
        board4[3][3]='mmmm'
        board6[3][3]='mmmm'
        board3[3][4]='mmmmmmmmm'
        board4[3][4]='    '
        board6[3][4]='    '
        board3[3][5]='         '
        board4[3][5]='    '
        board6[3][5]='    '
        board3[3][6]='         '
        board4[3][6]='    '
        board6[3][6]='    '
        board3[3][7]='         '
        board4[3][7]='    '
        board6[3][7]='    '

        board[0][3]='m'
        board2[0][3]='m'
        board[3][3]='m'
        board2[3][3]='m'

        board3[4][0]='mmmmmmmmm'
        board4[4][0]='mmmm'
        board6[4][0]='mmmm'
        board3[4][1]='         '
        board4[4][1]='    '
        board6[4][1]='    '
        board3[4][2]='         '
        board4[4][2]='    '
        board6[4][2]='    '
        board3[4][3]='         '
        board4[4][3]='mmmm'
        board6[4][3]='mmmm'
        board3[4][4]='mmmmmmmmm'
        board4[4][4]='    '
        board6[4][4]='    '
        board3[4][5]='         '
        board4[4][5]='    '
        board6[4][5]='    '
        board3[4][6]='         '
        board4[4][6]='    '
        board6[4][6]='    '
        board3[4][7]='         '
        board4[4][7]='    '
        board6[4][7]='    '

        board[0][4]='m'
        board2[0][4]='m'
        board[3][4]='m'
        board2[3][4]='m'

        board3[5][0]='mmmmmmmmm'
        board4[5][0]='mmmm'
        board6[5][0]='mmmm'
        board3[5][1]='         '
        board4[5][1]='    '
        board6[5][1]='    '
        board3[5][2]='         '
        board4[5][2]='    '
        board6[5][2]='    '
        board3[5][3]='         '
        board4[5][3]='    '
        board6[5][3]='    '
        board3[5][4]='         '
        board4[5][4]='    '
        board6[5][4]='    '
        board3[5][5]='         '
        board4[5][5]='    '
        board6[5][5]='    '
        board3[5][6]='         '
        board4[5][6]='    '
        board6[5][6]='    '
        board3[5][7]='         '
        board4[5][7]='    '
        board6[5][7]='    '

        board[0][5]='m'
        board2[0][5]='m'
        
        board3[6][0]='         '
        board4[6][0]='    '
        board6[6][0]='    '
        board3[6][1]='         '
        board4[6][1]='    '
        board6[6][1]='    '
        board3[6][2]='         '
        board4[6][2]='    '
        board6[6][2]='    '
        board3[6][3]='         '
        board4[6][3]='    '
        board6[6][3]='    '
        board3[6][4]='         '
        board4[6][4]='    '
        board6[6][4]='    '
        board3[6][5]='         '
        board4[6][5]='    '
        board6[6][5]='    '
        board3[6][6]='         '
        board4[6][6]='    '
        board6[6][6]='    '
        board3[6][7]='         '
        board4[6][7]='    '
        board6[6][7]='    '

        

        board3[7][0]='         '
        board4[7][0]='    '
        board6[7][0]='    '
        board3[7][1]='         '
        board4[7][1]='    '
        board6[7][1]='    '
        board3[7][2]='         '
        board4[7][2]='    '
        board6[7][2]='    '
        board3[7][3]='         '
        board4[7][3]='    '
        board6[7][3]='    '
        board3[7][4]='         '
        board4[7][4]='    '
        board6[7][4]='    '
        board3[7][5]='         '
        board4[7][5]='    '
        board6[7][5]='    '
        board3[7][6]='         '
        board4[7][6]='    '
        board6[7][6]='    '
        board3[7][7]='         '
        board4[7][7]='    '
        board6[7][7]='    '

    elif board5=='I':
        for x in range(8):
            for y in range(8):
                board[x][y] = ' '
                board2[x][y] = ' '
        board3[0][0]='         '
        board4[0][0]='    '
        board6[0][0]='    '
        board3[0][1]='         '
        board4[0][1]='    '
        board6[0][1]='    '
        board3[0][2]='         '
        board4[0][2]='    '
        board6[0][2]='    '
        board3[0][3]='         '
        board4[0][3]='    '
        board6[0][3]='    '
        board3[0][4]='         '
        board4[0][4]='    '
        board6[0][4]='    '
        board3[0][5]='         '
        board4[0][5]='    '
        board6[0][5]='    '
        board3[0][6]='         '
        board4[0][6]='    '
        board6[0][6]='    '
        board3[0][7]='         '
        board4[0][7]='    '
        board6[0][7]='    '

        

        board3[1][0]='         '
        board4[1][0]='    '
        board6[1][0]='    '
        board3[1][1]='         '
        board4[1][1]='    '
        board6[1][1]='    '
        board3[1][2]='         '
        board4[1][2]='    '
        board6[1][2]='    '
        board3[1][3]='         '
        board4[1][3]='    '
        board6[1][3]='    '
        board3[1][4]='         '
        board4[1][4]='    '
        board6[1][4]='    '
        board3[1][5]='         '
        board4[1][5]='    '
        board6[1][5]='    '
        board3[1][6]='         '
        board4[1][6]='    '
        board6[1][6]='    '
        board3[1][7]='         '
        board4[1][7]='    '
        board6[1][7]='    '

        

        board3[2][0]='mmmmmmmmm'
        board4[2][0]='mmmm'
        board6[2][0]='mmmm'
        board3[2][1]='         '
        board4[2][1]='    '
        board6[2][1]='    '
        board3[2][2]='         '
        board4[2][2]='    '
        board6[2][2]='    '
        board3[2][3]='         '
        board4[2][3]='    '
        board6[2][3]='    '
        board3[2][4]='         '
        board4[2][4]='    '
        board6[2][4]='    '
        board3[2][5]='         '
        board4[2][5]='    '
        board6[2][5]='    '
        board3[2][6]='         '
        board4[2][6]='    '
        board6[2][6]='    '
        board3[2][7]='mmmmmmmmm'
        board4[2][7]='mmmm'
        board6[2][7]='mmmm'

        board[0][2]='m'
        board2[0][2]='m'
        board[7][2]='m'
        board2[7][2]='m'

        board3[3][0]='mmmmmmmmm'
        board4[3][0]='mmmm'
        board6[3][0]='mmmm'
        board3[3][1]='mmmmmmmmm'
        board4[3][1]='mmmm'
        board6[3][1]='mmmm'
        board3[3][2]='mmmmmmmmm'
        board4[3][2]='mmmm'
        board6[3][2]='mmmm'
        board3[3][3]='mmmmmmmmm'
        board4[3][3]='mmmm'
        board6[3][3]='mmmm'
        board3[3][4]='mmmmmmmmm'
        board4[3][4]='mmmm'
        board6[3][4]='mmmm'
        board3[3][5]='mmmmmmmmm'
        board4[3][5]='mmmm'
        board6[3][5]='mmmm'
        board3[3][6]='mmmmmmmmm'
        board4[3][6]='mmmm'
        board6[3][6]='mmmm'
        board3[3][7]='mmmmmmmmm'
        board4[3][7]='mmmm'
        board6[3][7]='mmmm'

        board[0][3]='m'
        board2[0][3]='m'
        board[1][3]='m'
        board2[1][3]='m'
        board[2][3]='m'
        board2[2][3]='m'
        board[3][3]='m'
        board2[3][3]='m'
        board[4][3]='m'
        board2[4][3]='m'
        board[5][3]='m'
        board2[5][3]='m'
        board[6][3]='m'
        board2[6][3]='m'
        board[7][3]='m'
        board2[7][3]='m'

        board3[4][0]='mmmmmmmmm'
        board4[4][0]='mmmm'
        board6[4][0]='mmmm'
        board3[4][1]='mmmmmmmmm'
        board4[4][1]='mmmm'
        board6[4][1]='mmmm'
        board3[4][2]='mmmmmmmmm'
        board4[4][2]='mmmm'
        board6[4][2]='mmmm'
        board3[4][3]='mmmmmmmmm'
        board4[4][3]='mmmm'
        board6[4][3]='mmmm'
        board3[4][4]='mmmmmmmmm'
        board4[4][4]='mmmm'
        board6[4][4]='mmmm'
        board3[4][5]='mmmmmmmmm'
        board4[4][5]='mmmm'
        board6[4][5]='mmmm'
        board3[4][6]='mmmmmmmmm'
        board4[4][6]='mmmm'
        board6[4][6]='mmmm'
        board3[4][7]='mmmmmmmmm'
        board4[4][7]='mmmm'
        board6[4][7]='mmmm'

        board[0][4]='m'
        board2[0][4]='m'
        board[1][4]='m'
        board2[1][4]='m'
        board[2][4]='m'
        board2[2][4]='m'
        board[3][4]='m'
        board2[3][4]='m'
        board[4][4]='m'
        board2[4][4]='m'
        board[5][4]='m'
        board2[5][4]='m'
        board[6][4]='m'
        board2[6][4]='m'
        board[7][4]='m'
        board2[7][4]='m'

        board3[5][0]='mmmmmmmmm'
        board4[5][0]='mmmm'
        board6[5][0]='mmmm'
        board3[5][1]='         '
        board4[5][1]='    '
        board6[5][1]='    '
        board3[5][2]='         '
        board4[5][2]='    '
        board6[5][2]='    '
        board3[5][3]='         '
        board4[5][3]='    '
        board6[5][3]='    '
        board3[5][4]='         '
        board4[5][4]='    '
        board6[5][4]='    '
        board3[5][5]='         '
        board4[5][5]='    '
        board6[5][5]='    '
        board3[5][6]='         '
        board4[5][6]='    '
        board6[5][6]='    '
        board3[5][7]='mmmmmmmmm'
        board4[5][7]='mmmm'
        board6[5][7]='mmmm'

        board[0][5]='m'
        board2[0][5]='m'
        board[7][5]='m'
        board2[7][5]='m'
        
        board3[6][0]='         '
        board4[6][0]='    '
        board6[6][0]='    '
        board3[6][1]='         '
        board4[6][1]='    '
        board6[6][1]='    '
        board3[6][2]='         '
        board4[6][2]='    '
        board6[6][2]='    '
        board3[6][3]='         '
        board4[6][3]='    '
        board6[6][3]='    '
        board3[6][4]='         '
        board4[6][4]='    '
        board6[6][4]='    '
        board3[6][5]='         '
        board4[6][5]='    '
        board6[6][5]='    '
        board3[6][6]='         '
        board4[6][6]='    '
        board6[6][6]='    '
        board3[6][7]='         '
        board4[6][7]='    '
        board6[6][7]='    '

        

        board3[7][0]='         '
        board4[7][0]='    '
        board6[7][0]='    '
        board3[7][1]='         '
        board4[7][1]='    '
        board6[7][1]='    '
        board3[7][2]='         '
        board4[7][2]='    '
        board6[7][2]='    '
        board3[7][3]='         '
        board4[7][3]='    '
        board6[7][3]='    '
        board3[7][4]='         '
        board4[7][4]='    '
        board6[7][4]='    '
        board3[7][5]='         '
        board4[7][5]='    '
        board6[7][5]='    '
        board3[7][6]='         '
        board4[7][6]='    '
        board6[7][6]='    '
        board3[7][7]='         '
        board4[7][7]='    '
        board6[7][7]='    '

    elif board5=='.':
        for x in range(8):
            for y in range(8):
                board[x][y] = ' '
                board2[x][y] = ' '
        board3[0][0]='         '
        board4[0][0]='    '
        board6[0][0]='    '
        board3[0][1]='         '
        board4[0][1]='    '
        board6[0][1]='    '
        board3[0][2]='         '
        board4[0][2]='    '
        board6[0][2]='    '
        board3[0][3]='         '
        board4[0][3]='    '
        board6[0][3]='    '
        board3[0][4]='         '
        board4[0][4]='    '
        board6[0][4]='    '
        board3[0][5]='         '
        board4[0][5]='    '
        board6[0][5]='    '
        board3[0][6]='         '
        board4[0][6]='    '
        board6[0][6]='    '
        board3[0][7]='         '
        board4[0][7]='    '
        board6[0][7]='    '

        

        board3[1][0]='         '
        board4[1][0]='    '
        board6[1][0]='    '
        board3[1][1]='         '
        board4[1][1]='    '
        board6[1][1]='    '
        board3[1][2]='         '
        board4[1][2]='    '
        board6[1][2]='    '
        board3[1][3]='         '
        board4[1][3]='    '
        board6[1][3]='    '
        board3[1][4]='         '
        board4[1][4]='    '
        board6[1][4]='    '
        board3[1][5]='         '
        board4[1][5]='    '
        board6[1][5]='    '
        board3[1][6]='         '
        board4[1][6]='    '
        board6[1][6]='    '
        board3[1][7]='         '
        board4[1][7]='    '
        board6[1][7]='    '

        

        board3[2][0]='         '
        board4[2][0]='    '
        board6[2][0]='    '
        board3[2][1]='         '
        board4[2][1]='    '
        board6[2][1]='    '
        board3[2][2]='         '
        board4[2][2]='    '
        board6[2][2]='    '
        board3[2][3]='         '
        board4[2][3]='    '
        board6[2][3]='    '
        board3[2][4]='         '
        board4[2][4]='    '
        board6[2][4]='    '
        board3[2][5]='         '
        board4[2][5]='    '
        board6[2][5]='    '
        board3[2][6]='         '
        board4[2][6]='    '
        board6[2][6]='    '
        board3[2][7]='         '
        board4[2][7]='    '
        board6[2][7]='    '

        

        board3[3][0]='         '
        board4[3][0]='    '
        board6[3][0]='    '
        board3[3][1]='         '
        board4[3][1]='    '
        board6[3][1]='    '
        board3[3][2]='         '
        board4[3][2]='    '
        board6[3][2]='    '
        board3[3][3]='         '
        board4[3][3]='    '
        board6[3][3]='    '
        board3[3][4]='         '
        board4[3][4]='    '
        board6[3][4]='    '
        board3[3][5]='         '
        board4[3][5]='    '
        board6[3][5]='    '
        board3[3][6]='mmmmmmmmm'
        board4[3][6]='mmmm'
        board6[3][6]='mmmm'
        board3[3][7]='mmmmmmmmm'
        board4[3][7]='mmmm'
        board6[3][7]='mmmm'

        board[6][3]='m'
        board2[6][3]='m'
        board[7][3]='m'
        board2[7][3]='m'

        board3[4][0]='         '
        board4[4][0]='    '
        board6[4][0]='    '
        board3[4][1]='         '
        board4[4][1]='    '
        board6[4][1]='    '
        board3[4][2]='         '
        board4[4][2]='    '
        board6[4][2]='    '
        board3[4][3]='         '
        board4[4][3]='    '
        board6[4][3]='    '
        board3[4][4]='         '
        board4[4][4]='    '
        board6[4][4]='    '
        board3[4][5]='         '
        board4[4][5]='    '
        board6[4][5]='    '
        board3[4][6]='mmmmmmmmm'
        board4[4][6]='mmmm'
        board6[4][6]='mmmm'
        board3[4][7]='mmmmmmmmm'
        board4[4][7]='mmmm'
        board6[4][7]='mmmm'

        board[6][4]='m'
        board2[6][4]='m'
        board[7][4]='m'
        board2[7][4]='m'

        board3[5][0]='         '
        board4[5][0]='    '
        board6[5][0]='    '
        board3[5][1]='         '
        board4[5][1]='    '
        board6[5][1]='    '
        board3[5][2]='         '
        board4[5][2]='    '
        board6[5][2]='    '
        board3[5][3]='         '
        board4[5][3]='    '
        board6[5][3]='    '
        board3[5][4]='         '
        board4[5][4]='    '
        board6[5][4]='    '
        board3[5][5]='         '
        board4[5][5]='    '
        board6[5][5]='    '
        board3[5][6]='         '
        board4[5][6]='    '
        board6[5][6]='    '
        board3[5][7]='         '
        board4[5][7]='    '
        board6[5][7]='    '

        
        
        board3[6][0]='         '
        board4[6][0]='    '
        board6[6][0]='    '
        board3[6][1]='         '
        board4[6][1]='    '
        board6[6][1]='    '
        board3[6][2]='         '
        board4[6][2]='    '
        board6[6][2]='    '
        board3[6][3]='         '
        board4[6][3]='    '
        board6[6][3]='    '
        board3[6][4]='         '
        board4[6][4]='    '
        board6[6][4]='    '
        board3[6][5]='         '
        board4[6][5]='    '
        board6[6][5]='    '
        board3[6][6]='         '
        board4[6][6]='    '
        board6[6][6]='    '
        board3[6][7]='         '
        board4[6][7]='    '
        board6[6][7]='    '

        

        board3[7][0]='         '
        board4[7][0]='    '
        board6[7][0]='    '
        board3[7][1]='         '
        board4[7][1]='    '
        board6[7][1]='    '
        board3[7][2]='         '
        board4[7][2]='    '
        board6[7][2]='    '
        board3[7][3]='         '
        board4[7][3]='    '
        board6[7][3]='    '
        board3[7][4]='         '
        board4[7][4]='    '
        board6[7][4]='    '
        board3[7][5]='         '
        board4[7][5]='    '
        board6[7][5]='    '
        board3[7][6]='         '
        board4[7][6]='    '
        board6[7][6]='    '
        board3[7][7]='         '
        board4[7][7]='    '
        board6[7][7]='    '
                
def getNewBoard():
   
    board = []
    for i in range(8):
        board.append([' '] * 8)

    return board

def getBoardWithChessPices(board5,frame,numbers,instructions):
    board=getNewBoard()
    board2=getNewBoard()
    board3=getNewBoard()
    board4=getNewBoard()
    board6=getNewBoard()
    for x in range(8):
        for y in range(8):
            board[x][y] = ' '
            board2[x][y] = ' '
            board3[x][y] = ' '
            board4[x][y] = ' '
            board6[x][y] = ' '
    resetBoard(board,board2)
    getBlankChessBoard(board,board2,board3,board4,board5,board6)
    drawBoard(board,board2,board3,board4,board6,frame=frame,numbers=numbers,instructions=instructions)

def writeOnBoard(text,hello=False):
    text=text.upper()
    if len(text)==0:
        getBoardWithChessPices(board5=' ',frame=False,numbers=False,instructions=False)
    else:
        if(hello):
            writeOnBoard('hello ')
        for letter in range(0,len(text)):
            if text[letter] in letters:
                getBoardWithChessPices(board5=text[letter],frame=False,numbers=False,instructions=False)
                print()
        if(hello):
            writeOnBoard(' !')

if __name__=='__main__':
    if(write):
        name=input('Enter your nickname\t')
        writeOnBoard(name)
    else:
        writeOnBoard('h.i.',True)
    




elif board5=='I':
        for x in range(8):
            for y in range(8):
                board[x][y] = ' '
                board2[x][y] = ' '
        board3[0][0]='         '
        board4[0][0]='    '
        board6[0][0]='    '
        board3[0][1]='         '
        board4[0][1]='    '
        board6[0][1]='    '
        board3[0][2]='         '
        board4[0][2]='    '
        board6[0][2]='    '
        board3[0][3]='         '
        board4[0][3]='    '
        board6[0][3]='    '
        board3[0][4]='         '
        board4[0][4]='    '
        board6[0][4]='    '
        board3[0][5]='         '
        board4[0][5]='    '
        board6[0][5]='    '
        board3[0][6]='         '
        board4[0][6]='    '
        board6[0][6]='    '
        board3[0][7]='         '
        board4[0][7]='    '
        board6[0][7]='    '

        

        board3[1][0]='         '
        board4[1][0]='    '
        board6[1][0]='    '
        board3[1][1]='         '
        board4[1][1]='    '
        board6[1][1]='    '
        board3[1][2]='         '
        board4[1][2]='    '
        board6[1][2]='    '
        board3[1][3]='         '
        board4[1][3]='    '
        board6[1][3]='    '
        board3[1][4]='         '
        board4[1][4]='    '
        board6[1][4]='    '
        board3[1][5]='         '
        board4[1][5]='    '
        board6[1][5]='    '
        board3[1][6]='         '
        board4[1][6]='    '
        board6[1][6]='    '
        board3[1][7]='         '
        board4[1][7]='    '
        board6[1][7]='    '

        

        board3[2][0]='         '
        board4[2][0]='    '
        board6[2][0]='    '
        board3[2][1]='         '
        board4[2][1]='    '
        board6[2][1]='    '
        board3[2][2]='         '
        board4[2][2]='    '
        board6[2][2]='    '
        board3[2][3]='         '
        board4[2][3]='    '
        board6[2][3]='    '
        board3[2][4]='         '
        board4[2][4]='    '
        board6[2][4]='    '
        board3[2][5]='         '
        board4[2][5]='    '
        board6[2][5]='    '
        board3[2][6]='         '
        board4[2][6]='    '
        board6[2][6]='    '
        board3[2][7]='         '
        board4[2][7]='    '
        board6[2][7]='    '

        

        board3[3][0]='         '
        board4[3][0]='    '
        board6[3][0]='    '
        board3[3][1]='         '
        board4[3][1]='    '
        board6[3][1]='    '
        board3[3][2]='         '
        board4[3][2]='    '
        board6[3][2]='    '
        board3[3][3]='         '
        board4[3][3]='    '
        board6[3][3]='    '
        board3[3][4]='         '
        board4[3][4]='    '
        board6[3][4]='    '
        board3[3][5]='         '
        board4[3][5]='    '
        board6[3][5]='    '
        board3[3][6]='         '
        board4[3][6]='    '
        board6[3][6]='    '
        board3[3][7]='         '
        board4[3][7]='    '
        board6[3][7]='    '

        

        board3[4][0]='         '
        board4[4][0]='    '
        board6[4][0]='    '
        board3[4][1]='         '
        board4[4][1]='    '
        board6[4][1]='    '
        board3[4][2]='         '
        board4[4][2]='    '
        board6[4][2]='    '
        board3[4][3]='         '
        board4[4][3]='    '
        board6[4][3]='    '
        board3[4][4]='         '
        board4[4][4]='    '
        board6[4][4]='    '
        board3[4][5]='         '
        board4[4][5]='    '
        board6[4][5]='    '
        board3[4][6]='         '
        board4[4][6]='    '
        board6[4][6]='    '
        board3[4][7]='         '
        board4[4][7]='    '
        board6[4][7]='    '

        

        board3[5][0]='         '
        board4[5][0]='    '
        board6[5][0]='    '
        board3[5][1]='         '
        board4[5][1]='    '
        board6[5][1]='    '
        board3[5][2]='         '
        board4[5][2]='    '
        board6[5][2]='    '
        board3[5][3]='         '
        board4[5][3]='    '
        board6[5][3]='    '
        board3[5][4]='         '
        board4[5][4]='    '
        board6[5][4]='    '
        board3[5][5]='         '
        board4[5][5]='    '
        board6[5][5]='    '
        board3[5][6]='         '
        board4[5][6]='    '
        board6[5][6]='    '
        board3[5][7]='         '
        board4[5][7]='    '
        board6[5][7]='    '

        
        
        board3[6][0]='         '
        board4[6][0]='    '
        board6[6][0]='    '
        board3[6][1]='         '
        board4[6][1]='    '
        board6[6][1]='    '
        board3[6][2]='         '
        board4[6][2]='    '
        board6[6][2]='    '
        board3[6][3]='         '
        board4[6][3]='    '
        board6[6][3]='    '
        board3[6][4]='         '
        board4[6][4]='    '
        board6[6][4]='    '
        board3[6][5]='         '
        board4[6][5]='    '
        board6[6][5]='    '
        board3[6][6]='         '
        board4[6][6]='    '
        board6[6][6]='    '
        board3[6][7]='         '
        board4[6][7]='    '
        board6[6][7]='    '

        

        board3[7][0]='         '
        board4[7][0]='    '
        board6[7][0]='    '
        board3[7][1]='         '
        board4[7][1]='    '
        board6[7][1]='    '
        board3[7][2]='         '
        board4[7][2]='    '
        board6[7][2]='    '
        board3[7][3]='         '
        board4[7][3]='    '
        board6[7][3]='    '
        board3[7][4]='         '
        board4[7][4]='    '
        board6[7][4]='    '
        board3[7][5]='         '
        board4[7][5]='    '
        board6[7][5]='    '
        board3[7][6]='         '
        board4[7][6]='    '
        board6[7][6]='    '
        board3[7][7]='         '
        board4[7][7]='    '
        board6[7][7]='    '
